EXOPLANET HABITABILITY CLASSIFICATION END-TO-END PROJECT

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as pyplot

In [3]:
df = pd.read_csv("hwc.csv")
df.head()

,P_NAME,P_DETECTION,P_DISCOVERY_FACILITY,P_YEAR,P_UPDATE,P_MASS,P_MASS_ERROR_MIN,P_MASS_ERROR_MAX,P_MASS_LIMIT,P_MASS_ORIGIN,...,S_ABIO_ZONE,S_TIDAL_LOCK,P_HABZONE_OPT,P_HABZONE_CON,P_TYPE_TEMP,P_HABITABLE,P_ESI,S_CONSTELLATION,S_CONSTELLATION_ABR,S_CONSTELLATION_ENG
0,OGLE-2016-BLG-1227L b,Microlensing,OGLE,2020,2020-04-02,250.00,-120.0,413.0,0,Mass,...,NaN,0.214133,0,0,NaN,0,NaN,Scorpius,Sco,Scorpion
1,Kepler-276 c,Transit,Kepler,2013,2018-09-25,16.60,-3.6,4.4,0,Mass,...,2.097783,0.316980,0,0,Hot,0,0.272032,Cygnus,Cyg,Swan
2,Kepler-829 b,Transit,Kepler,2016,2019-04-16,5.10,NaN,NaN,0,M-R relationship,...,1.756317,0.459559,0,0,Hot,0,0.254763,Lyra,Lyr,Lyre
3,K2-283 b,Transit,K2,2018,2019-09-05,12.20,NaN,NaN,0,M-R relationship,...,0.568374,0.443760,0,0,Hot,0,0.193906,Pisces,Psc,Fishes
4,Kepler-477 b,Transit,Kepler,2016,2019-04-16,4.94,NaN,NaN,0,M-R relationship,...,0.768502,0.386150,0,0,Hot,0,0.276721,Lyra,Lyr,Lyre

In [6]:
df.columns

Index(['P_NAME', 'P_DETECTION', 'P_DISCOVERY_FACILITY', 'P_YEAR', 'P_UPDATE',
       'P_MASS', 'P_MASS_ERROR_MIN', 'P_MASS_ERROR_MAX', 'P_MASS_LIMIT',
       'P_MASS_ORIGIN',
       ...
       'S_ABIO_ZONE', 'S_TIDAL_LOCK', 'P_HABZONE_OPT', 'P_HABZONE_CON',
       'P_TYPE_TEMP', 'P_HABITABLE', 'P_ESI', 'S_CONSTELLATION',
       'S_CONSTELLATION_ABR', 'S_CONSTELLATION_ENG'],
      dtype='object', length=118)

In [13]:
shape = df.shape
print(f'Rows: {shape[0]}')
print(f'Columns: {shape[1]}')

Rows: 5599
Columns: 118

In [23]:
df.isnull().sum()

P_NAME                    0
P_DETECTION               0
P_DISCOVERY_FACILITY      0
P_YEAR                    0
P_UPDATE                  0
                       ...
P_HABITABLE               0
P_ESI                   241
S_CONSTELLATION           0
S_CONSTELLATION_ABR       0
S_CONSTELLATION_ENG       0
Length: 118, dtype: int64

In [27]:
df.dropna(inplace=True)

In [28]:
df.isnull().sum()

P_NAME                  0
P_DETECTION             0
P_DISCOVERY_FACILITY    0
P_YEAR                  0
P_UPDATE                0
                       ..
P_HABITABLE             0
P_ESI                   0
S_CONSTELLATION         0
S_CONSTELLATION_ABR     0
S_CONSTELLATION_ENG     0
Length: 118, dtype: int64

In this dataset, we do not have a direct target column indicating whether an exoplanet is habitable or not. However, based on NASA’s classification criteria, exoplanets classified as warm, subterran, terran, or superterran are considered potentially habitable. These exoplanets can be further evaluated using the Earth Similarity Index (ESI), which measures how similar an exoplanet is to Earth based on factors such as size, temperature, and other planetary characteristics. In general, exoplanets with an ESI greater than 0.5 are considered potentially habitable. Therefore, the ESI and planetary classification can be used to derive a target variable for our analysis.

In [36]:
# def target(df):
#     if 'P_ESI' in df.columns:
#         df['habitability'] = pd.cut(df['P_ESI'], bins=[ 0, 0.2, 0.5, 1.0],
#         labels=['Non-Habitable', 'Potentially-Habitable', 'Habitable'])
#         return df


def target(df):
    if 'P_ESI' in df.columns:
        # Drop rows with missing ESI
        df = df.dropna(subset=['P_ESI'])
        
        df['habitability'] = pd.cut(df['P_ESI'], 
                                    bins=[0, 0.2, 0.5, 1.0],
                                    labels=['Non-Habitable', 'Potentially-Habitable', 'Habitable'])
        return df

df = target(df)
print(df['habitability'].value_counts())

habitability
Potentially-Habitable    13
Non-Habitable             0
Habitable                 0
Name: count, dtype: int64

In [32]:
df.head()

,P_NAME,P_DETECTION,P_DISCOVERY_FACILITY,P_YEAR,P_UPDATE,P_MASS,P_MASS_ERROR_MIN,P_MASS_ERROR_MAX,P_MASS_LIMIT,P_MASS_ORIGIN,...,S_TIDAL_LOCK,P_HABZONE_OPT,P_HABZONE_CON,P_TYPE_TEMP,P_HABITABLE,P_ESI,S_CONSTELLATION,S_CONSTELLATION_ABR,S_CONSTELLATION_ENG,habitability
27,HD 86226 c,Transit,Transiting Exoplanet Survey Satellite (TESS),2020,2024-03-04,7.25,-1.12,1.19,0,Mass,...,0.464392,0,0,Hot,0,0.249443,Hydra,Hya,Water Snake,Potentially-Habitable
48,55 Cnc e,Radial Velocity,McDonald Observatory,2004,2024-03-04,7.99,-0.33,0.32,0,Mass,...,0.510511,0,0,Hot,0,0.261376,Cancer,Cnc,Crab,Potentially-Habitable
127,HD 97658 b,Radial Velocity,W. M. Keck Observatory,2010,2024-03-04,8.30,-1.10,1.10,0,Mass,...,0.425150,0,0,Hot,0,0.272778,Leo,Leo,Lion,Potentially-Habitable
131,HD 5278 b,Transit,Transiting Exoplanet Survey Satellite (TESS),2021,2024-03-04,7.80,-1.40,1.50,0,Mass,...,0.447477,0,0,Hot,0,0.242747,Octans,Oct,Octant,Potentially-Habitable
166,HD 110113 b,Transit,Transiting Exoplanet Survey Satellite (TESS),2021,2024-03-04,4.55,-0.62,0.62,0,Mass,...,0.450714,0,0,Hot,0,0.253917,Centaurus,Cen,Centaur,Potentially-Habitable